import { DependencyContainer } from "tsyringe";
import { CompanyRepository } from "../company-repository";
import { PrivilegeRepository } from "../privilege-repository";
import { RoleRepository } from "../role-repository";
import { UserRepository } from "../user-repository";
import { ToDoRepository } from "../todo-repository";
import { VerificationRepository } from "../verification-repository";
import { DepartmentRepository } from "../department-repository";
import { DesignationRepository } from "../designation-repository";
import { CandidateRepository } from "../candidate-repository";
import { ProjectRepository } from "../project-repository";
import { SkillRepository } from "../skill-repository";
import { AssessmentRepository } from "../assessment-repository";
import { AssessmentScoreRepository } from "../assessment-score-repository";
import { CountryRepository } from "../country-repository";
import { LeaveTypeRepository } from "../leave-type-repository";
import { PublicHolidayRepository } from "../public-holiday-repository";
import { EmployeeRepository } from "../employee-repository";
import { AttendanceRepository } from "../attendance-repository";
import { AttendanceBreakRepository } from "../attendance-break-repository";
import { VacationRepository } from "../vacation-repository";
import { WorkingDaysRepository } from "../working-days-repository";
import { ShiftRepository } from "../shift-repository";
import { UserShiftRepository } from "../user-shift-repository";
import { SchedulerRepository } from "../scheduler-repository";
import { MasterEnumRepository } from "../master-enum-repository";
import { InviteRepository } from "../invite-repository";
import { RequestRepository } from "../request-repository";
import { BenefitRepository } from "../benefit-repository";
import { EmployeeBenefitRepository } from "../employee-benefit-repository";
import { PayrollRepository } from "../payroll-repository";
import { PayrollAdjustmentRepository } from "../payroll-adjustment-repository";
import { AttendanceSummaryRepository } from "../attendance-summary-repository";
import { AnnouncementRepository } from "../announcement-repository";
import { NotificationRepository } from "../notification-repository";


export const registerRepositories = (container: DependencyContainer) => {
    container.register<CompanyRepository>('CompanyRepository', CompanyRepository);
    container.register<CountryRepository>('CountryRepository', CountryRepository);
    container.register<MasterEnumRepository>('MasterEnumRepository', MasterEnumRepository);
    container.register<UserRepository>('UserRepository', UserRepository);
    container.register<PrivilegeRepository>('PrivilegeRepository', PrivilegeRepository);
    container.register<RoleRepository>('RoleRepository', RoleRepository );
    container.register<ToDoRepository>('ToDoRepository', ToDoRepository );
    container.register<VerificationRepository>('VerificationRepository', VerificationRepository );
    container.register<DepartmentRepository>('DepartmentRepository', DepartmentRepository);
    container.register<DesignationRepository>('DesignationRepository', DesignationRepository);
    container.register<CandidateRepository>('CandidateRepository', CandidateRepository);
    container.register<ProjectRepository>('ProjectRepository', ProjectRepository);
    container.register<SkillRepository>('SkillRepository', SkillRepository);
    container.register<AssessmentRepository>('AssessmentRepository', AssessmentRepository);
    container.register<AssessmentScoreRepository>('AssessmentScoreRepository', AssessmentScoreRepository);
    container.register<LeaveTypeRepository>('LeaveTypeRepository', LeaveTypeRepository);
    container.register<PublicHolidayRepository>('PublicHolidayRepository', PublicHolidayRepository);
    container.register<EmployeeRepository>('EmployeeRepository', EmployeeRepository);
    container.register<AttendanceRepository>('AttendanceRepository', AttendanceRepository);
    container.register<AttendanceBreakRepository>('AttendanceBreakRepository', AttendanceBreakRepository);
    container.register<VacationRepository>('VacationRepository', VacationRepository);
    container.register<WorkingDaysRepository>('WorkingDaysRepository', WorkingDaysRepository);
    container.register<ShiftRepository>('ShiftRepository', ShiftRepository);
    container.register<UserShiftRepository>('UserShiftRepository', UserShiftRepository);
    container.register<SchedulerRepository>('SchedulerRepository', SchedulerRepository);
    container.register<InviteRepository>('InviteRepository', InviteRepository);
    container.register<RequestRepository>('RequestRepository', RequestRepository);
    container.register<BenefitRepository>('BenefitRepository', BenefitRepository);
    container.register<EmployeeBenefitRepository>('EmployeeBenefitRepository', EmployeeBenefitRepository);
    container.register<PayrollRepository>('PayrollRepository', PayrollRepository);
    container.register<PayrollAdjustmentRepository>('PayrollAdjustmentRepository', PayrollAdjustmentRepository);
    container.register<AttendanceSummaryRepository>('AttendanceSummaryRepository', AttendanceSummaryRepository);
    container.register<AnnouncementRepository>('AnnouncementRepository', AnnouncementRepository);
    container.register<NotificationRepository>('NotificationRepository', NotificationRepository);
}