import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1700000000000 implements MigrationInterface {
    name = 'InitialSchema1700000000000'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "Privilege" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "name" text NOT NULL, "code" text NOT NULL, "module" character varying NOT NULL, CONSTRAINT "UQ_b3b51ee1e6081d4a698a5f01dd8" UNIQUE ("name"), CONSTRAINT "UQ_f9a5a7a48c2646f539d3d87894c" UNIQUE ("code"), CONSTRAINT "PK_a30819d5c85e3467afe51f9ed27" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."Verification_type_enum" AS ENUM('email', 'phone')`);
        await queryRunner.query(`CREATE TYPE "public"."Verification_whichpurpose_enum" AS ENUM('accountVerify', 'forgotPassword')`);
        await queryRunner.query(`CREATE TABLE "Verification" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "target" character varying(255) NOT NULL, "code" character varying(10) NOT NULL, "url" character varying(255), "type" "public"."Verification_type_enum", "whichPurpose" "public"."Verification_whichpurpose_enum", "verified" boolean NOT NULL DEFAULT false, "expiresAt" TIMESTAMP, "userId" uuid, CONSTRAINT "PK_c088fa000872075adc40490961b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_31ffc38ebfed70d24cfeea84d6" ON "Verification" ("target") `);
        await queryRunner.query(`CREATE TYPE "public"."Designation_levelhierarchy_enum" AS ENUM('ENTRY', 'MID', 'SENIOR', 'LEAD', 'MANAGER', 'DIRECTOR')`);
        await queryRunner.query(`CREATE TABLE "Designation" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "departmentId" uuid, "title" character varying(255) NOT NULL, "code" character varying(50), "jobDescription" text, "levelHierarchy" "public"."Designation_levelhierarchy_enum" NOT NULL DEFAULT 'ENTRY', "responsibilities" text, "sortOrder" integer, CONSTRAINT "PK_9ce84d2519b60d2cc3a8b4f1845" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6042cd2ab7b046e181a4dba91a" ON "Designation" ("companyId", "title") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a18e8c0f02927b845e40d84f2f" ON "Designation" ("companyId", "code") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE TABLE "Country" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "name" text NOT NULL, "code" character varying(3) NOT NULL, "iso2" character varying(2) NOT NULL, "capital" text, "continent" text, "currency" text, "phone" text, CONSTRAINT "UQ_45be114be75911c60ca51371a65" UNIQUE ("name"), CONSTRAINT "UQ_04935d5bc71e6c49d43372a7720" UNIQUE ("code"), CONSTRAINT "UQ_74d6ebda87d57484c0ce12c6fa0" UNIQUE ("iso2"), CONSTRAINT "PK_43cb4419fc372b859dec2618037" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."PublicHoliday_type_enum" AS ENUM('NATIONAL', 'RELIGIOUS', 'CULTURAL', 'REGIONAL', 'COMPANY', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "PublicHoliday" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "name" character varying(255) NOT NULL, "dates" json NOT NULL, "isMultiple" boolean NOT NULL DEFAULT false, "type" "public"."PublicHoliday_type_enum", "description" text, "whichCountryId" uuid, "departmentId" uuid NOT NULL, CONSTRAINT "PK_238f6f59dd29feaa2bc8643ac7b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_89193a043b50b8c5e22803e5d2" ON "PublicHoliday" ("departmentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0718e184666cb9645d29a78e7a" ON "PublicHoliday" ("companyId", "departmentId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6e706c4bcc13d49c1550d9a308" ON "PublicHoliday" ("companyId", "name", "departmentId") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE TYPE "public"."WorkingDays_dayname_enum" AS ENUM('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')`);
        await queryRunner.query(`CREATE TABLE "WorkingDays" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "dayOfWeek" smallint NOT NULL, "dayName" "public"."WorkingDays_dayname_enum" NOT NULL, "isWorkingDay" boolean NOT NULL DEFAULT true, "notes" text, "departmentId" uuid, CONSTRAINT "UQ_4a403a10d3dacecc66dfa89a230" UNIQUE ("companyId", "dayOfWeek", "departmentId"), CONSTRAINT "PK_fb2798044d035205ed8ce53181a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4a403a10d3dacecc66dfa89a23" ON "WorkingDays" ("companyId", "dayOfWeek", "departmentId") `);
        await queryRunner.query(`CREATE TYPE "public"."Shift_shifttype_enum" AS ENUM('MORNING', 'EVENING', 'NIGHT', 'FLEXIBLE', 'ROTATIONAL')`);
        await queryRunner.query(`CREATE TABLE "Shift" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "name" character varying(255) NOT NULL, "code" character varying(50) NOT NULL, "shiftType" "public"."Shift_shifttype_enum" NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "workingHours" integer NOT NULL, "marginTime" integer NOT NULL DEFAULT '30', "breakDuration" integer NOT NULL DEFAULT '0', "order" integer NOT NULL DEFAULT '0', "departmentId" uuid, CONSTRAINT "PK_7ad7021c79529f4efeaceb5b874" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_712a6cd08fb8b534f23311277f" ON "Shift" ("companyId", "departmentId", "order") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_db8d7a9947738c01bfecaf08f0" ON "Shift" ("companyId", "name", "departmentId") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3915799d9806645f4f436b86ae" ON "Shift" ("companyId", "code", "departmentId") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE TABLE "Department" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "name" character varying(255) NOT NULL, "code" character varying(50), "description" text, "parentId" uuid, "sortOrder" integer, CONSTRAINT "PK_2db7d829a31533bd913ef432dc2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1fb48e609614d5b97b84941122" ON "Department" ("companyId", "name") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3eee0ade0f427f8d9f7f71a0ee" ON "Department" ("companyId", "code") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE TYPE "public"."Benefit_type_enum" AS ENUM('HEALTH', 'RETIREMENT', 'BONUS', 'INSURANCE', 'VACATION', 'EDUCATION', 'WELLNESS', 'TRANSPORTATION', 'OTHER')`);
        await queryRunner.query(`CREATE TYPE "public"."Benefit_valuetype_enum" AS ENUM('FIXED', 'PERCENTAGE')`);
        await queryRunner.query(`CREATE TYPE "public"."Benefit_frequency_enum" AS ENUM('MONTHLY', 'YEARLY', 'QUARTERLY', 'ONE_TIME')`);
        await queryRunner.query(`CREATE TABLE "Benefit" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "name" character varying(255) NOT NULL, "code" character varying(50), "description" text, "type" "public"."Benefit_type_enum" NOT NULL, "value" numeric(10,2), "valueType" "public"."Benefit_valuetype_enum", "frequency" "public"."Benefit_frequency_enum", "startDate" date, "endDate" date, "sortOrder" integer, "departmentId" uuid, CONSTRAINT "PK_eca4eaec42ce711a5f9c55ea5ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_08551d108120400623a97166ab" ON "Benefit" ("companyId", "name", "departmentId") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0c3ab6e3d475ec045deb56308a" ON "Benefit" ("companyId", "code", "departmentId") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE TYPE "public"."Employee_status_enum" AS ENUM('PERMANENT', 'PROBATION', 'CONTRACT', 'RESIGNED', 'TERMINATED', 'RETIRED')`);
        await queryRunner.query(`CREATE TABLE "Employee" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "userId" uuid NOT NULL, "employeeCode" text NOT NULL, "departmentId" uuid NOT NULL, "designationId" uuid NOT NULL, "shiftId" uuid, "joiningDate" date NOT NULL, "salary" numeric(12,2), "probationEndDate" date, "departureDate" date, "status" "public"."Employee_status_enum" NOT NULL DEFAULT 'PROBATION', "address" text, "phoneNumber" text, "emergencyContact" text, "bankName" text, "accountNumber" text, "ibanNumber" text, CONSTRAINT "UQ_b14229cf36bfd96e6a7187d85f0" UNIQUE ("companyId", "employeeCode"), CONSTRAINT "REL_c1ec0cb63387d4c8bb2892bc00" UNIQUE ("userId"), CONSTRAINT "PK_9a993c20751b9867abc60108433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "EmployeeBenefit" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "userId" uuid NOT NULL, "employeeId" uuid NOT NULL, "benefitId" uuid NOT NULL, "effectiveDate" date NOT NULL, "endDate" date, "customValue" numeric(10,2), "notes" text, CONSTRAINT "UQ_c669d5cdb8355a7b1153e2a7417" UNIQUE ("companyId", "employeeId", "benefitId"), CONSTRAINT "PK_b2b1af5515130f595ba695412d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."Project_status_enum" AS ENUM('todo', 'progress', 'blocked', 'done')`);
        await queryRunner.query(`CREATE TABLE "Project" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "name" character varying(255) NOT NULL, "owner" character varying(255), "status" "public"."Project_status_enum" NOT NULL DEFAULT 'todo', "progress" integer NOT NULL DEFAULT '0', "due" date, "note" text, CONSTRAINT "PK_2725f461500317f74b0c8f11859" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Role" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "name" text NOT NULL, "code" text NOT NULL, "isEditable" boolean NOT NULL DEFAULT true, "companyId" uuid, CONSTRAINT "UQ_4e63b16c2c19020a513260bbcd9" UNIQUE ("companyId", "name"), CONSTRAINT "UQ_e833d975a43cea809f84afe2409" UNIQUE ("companyId", "code"), CONSTRAINT "PK_9309532197a7397548e341e5536" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "User" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "userName" text NOT NULL, "email" text NOT NULL, "passwordHash" text, "firstName" text NOT NULL, "middleName" text, "lastName" text NOT NULL, "gender" text NOT NULL DEFAULT 'other', "pictureUrl" text, "dateOfBirth" TIMESTAMP, "status" integer NOT NULL DEFAULT '1', "lastLogin" TIMESTAMP, "lastOnline" TIMESTAMP, "roleId" uuid NOT NULL, "isEmailVerified" text, "isPhoneVerified" text, "phoneNumber" text, "isGoogleSignup" boolean NOT NULL DEFAULT false, "googleAccessToken" text, "googleRefreshToken" text, CONSTRAINT "UQ_4a257d2c9837248d70640b3e36e" UNIQUE ("email"), CONSTRAINT "UQ_de7bf128d7c38e3f0418410bca0" UNIQUE ("companyId", "userName"), CONSTRAINT "PK_9862f679340fb2388436a5ab3e4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Company" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "name" text NOT NULL, "phoneNo" text, "email" text NOT NULL, "address" text, "temporaryAddress" text, "zipCode" integer, "country" text, "state" text, "city" text, "logoUrl" text, "isSystemCompany" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_dce346cb64f739227d3910a77d2" UNIQUE ("name"), CONSTRAINT "UQ_1e86f3b42774f804f0adc6d78d9" UNIQUE ("email"), CONSTRAINT "PK_b4993a6b3d3194767a59698298f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "MasterEnum" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "moduleType" character varying(50) NOT NULL, "enumKey" character varying(100) NOT NULL, "enumValue" character varying(100) NOT NULL, "description" text, "isActive" boolean NOT NULL DEFAULT true, "sortOrder" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_695920782f52409d5b54deea6eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0b0e7a0342661f17cb2ab80cb9" ON "MasterEnum" ("moduleType", "enumKey") `);
        await queryRunner.query(`CREATE TABLE "ToDo" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "todo" text NOT NULL, "details" text NOT NULL, "dueDate" TIMESTAMP NOT NULL, "completed" boolean NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_af831d7ba28c8574834c7f7552a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "ActivityLog" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "logDetail" text NOT NULL, "url" text NOT NULL, "model" text NOT NULL, "method" text NOT NULL, "status" text NOT NULL, "platform" text, "language" text, "ipAddress" text, "params" json, "queryParams" json, "body" json, "headers" json, "errorDetail" text, "companyId" uuid, CONSTRAINT "PK_399093f65413d2893d656e75e6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "AuditLog" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "action" text NOT NULL, "model" text NOT NULL, "oldState" json, "newState" json, "message" text NOT NULL, "companyId" uuid, "entityId" uuid NOT NULL, "changedFields" json, CONSTRAINT "PK_1a89a74497128c612dbda3fe042" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."Candidate_stage_enum" AS ENUM('applied', 'screen', 'interview', 'offer', 'hired', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "Candidate" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "name" character varying(255) NOT NULL, "role" character varying(255) NOT NULL DEFAULT 'Unspecified role', "stage" "public"."Candidate_stage_enum" NOT NULL DEFAULT 'applied', "owner" character varying(255), "source" character varying(255), "date" date, "note" text, "currentCompany" character varying(255), "city" character varying(255), "email" character varying(255), "contact" character varying(100), "currentSalary" character varying(100), "expectedSalary" character varying(100), "score" integer, "notice" character varying(100), CONSTRAINT "PK_a31a8947b7261f49bdd66d29004" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Skill" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "name" character varying(120) NOT NULL, "key" character varying(120) NOT NULL, "description" text, "scaleMin" integer NOT NULL DEFAULT '0', "scaleMax" integer NOT NULL DEFAULT '10', "weight" numeric(6,2) NOT NULL DEFAULT '1', "sortOrder" integer, CONSTRAINT "PK_566c22ec29ed0c9cab8eb36ffbd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e1968c96fe4a16f80dbc4aab21" ON "Skill" ("companyId", "key") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE TABLE "AssessmentScore" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "assessmentId" uuid NOT NULL, "skillId" uuid NOT NULL, "score" numeric(6,2) NOT NULL, CONSTRAINT "PK_2b1bfbee56c2b4d46ad679fdb6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Assessment" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "employeeId" uuid NOT NULL, "assessedOn" date NOT NULL, "assessor" character varying(255), "note" text, CONSTRAINT "PK_37dc68e67f15a8973a33f8fa456" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d28f884c64218d820c06693a65" ON "Assessment" ("employeeId", "assessedOn") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE TYPE "public"."LeaveType_genderspecific_enum" AS ENUM('ALL', 'MALE', 'FEMALE')`);
        await queryRunner.query(`CREATE TABLE "LeaveType" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "departmentId" uuid, "name" character varying(255) NOT NULL, "code" character varying(50), "description" text, "maxDaysPerYear" integer NOT NULL DEFAULT '0', "maxConsecutiveDays" integer NOT NULL DEFAULT '0', "isPaid" boolean NOT NULL DEFAULT true, "requiresApproval" boolean NOT NULL DEFAULT true, "canBeCarriedForward" boolean NOT NULL DEFAULT false, "carryForwardLimit" integer NOT NULL DEFAULT '0', "genderSpecific" "public"."LeaveType_genderspecific_enum" NOT NULL DEFAULT 'ALL', CONSTRAINT "PK_70df5ccd91d22535eb284ccecc1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ee86dd2a9a510ee0b92d124d18" ON "LeaveType" ("companyId", "name") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f5d6eefea9367a9742b9a05226" ON "LeaveType" ("companyId", "code") WHERE "deleted" = false`);
        await queryRunner.query(`CREATE TABLE "Break" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "attendanceId" uuid NOT NULL, "userId" uuid NOT NULL, "breakType" text NOT NULL, "startTime" TIMESTAMP NOT NULL, "endTime" TIMESTAMP, "durationMinutes" integer, "notes" text, "location" text, "isActive" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_0e087ff22e90d982c7323ff8058" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7b6f6f0dcfa8f1bb0a6f49bb1b" ON "Break" ("userId", "startTime") `);
        await queryRunner.query(`CREATE TYPE "public"."Vacation_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."Vacation_progressstatus_enum" AS ENUM('IN_PROGRESS', 'COMPLETED')`);
        await queryRunner.query(`CREATE TYPE "public"."Vacation_requesttype_enum" AS ENUM('LEAVE', 'REMOTE_WORK')`);
        await queryRunner.query(`CREATE TABLE "Vacation" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "requestedBy" uuid NOT NULL, "fromDate" date NOT NULL, "toDate" date NOT NULL, "totalDays" integer NOT NULL DEFAULT '1', "reason" text NOT NULL, "typeId" uuid, "actionBy" uuid, "actionAt" TIMESTAMP, "status" "public"."Vacation_status_enum" NOT NULL DEFAULT 'PENDING', "progressStatus" "public"."Vacation_progressstatus_enum", "rejectionReason" text, "requestType" "public"."Vacation_requesttype_enum" NOT NULL DEFAULT 'LEAVE', CONSTRAINT "PK_2c178acd3ac440e2861586eaff3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_572b94fc3c022405e5fb377a9d" ON "Vacation" ("requestedBy", "companyId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_69caf3aded343eb70907d36a90" ON "Vacation" ("typeId", "status", "requestType") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1040e7608de80573a46702a7f" ON "Vacation" ("status", "companyId", "requestType") `);
        await queryRunner.query(`CREATE INDEX "IDX_5532ee2ca08742691f688d8d58" ON "Vacation" ("requestedBy", "fromDate", "toDate", "requestType") `);
        await queryRunner.query(`CREATE TYPE "public"."Attendance_status_enum" AS ENUM('DEFAULT', 'PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'ON_LEAVE', 'HOLIDAY', 'DAY_OFF')`);
        await queryRunner.query(`CREATE TYPE "public"."Attendance_presentstatus_enum" AS ENUM('CHECK_IN', 'CHECK_OUT', 'ON_BREAK')`);
        await queryRunner.query(`CREATE TABLE "Attendance" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "userId" uuid NOT NULL, "shiftId" uuid, "date" date NOT NULL, "checkInTime" TIME, "checkOutTime" TIME, "status" "public"."Attendance_status_enum" NOT NULL DEFAULT 'DEFAULT', "presentStatus" "public"."Attendance_presentstatus_enum", "lockWorkingHours" numeric(5,2), "totalWorkingHours" numeric(5,2), "minimumRequiredWorkingHour" numeric(5,2), "totalBreakTime" numeric(5,2), "lateMinutes" integer NOT NULL DEFAULT '0', "earlyLeaveMinutes" integer NOT NULL DEFAULT '0', "notes" text, "location" text, "isRemote" boolean NOT NULL DEFAULT false, "vacationId" uuid, "publicHolidayId" uuid, "remoteWorkId" uuid, CONSTRAINT "PK_137a8eec2cec8606cdf8f1e4f67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5742abb86c9f08df0f719e9571" ON "Attendance" ("userId", "date") `);
        await queryRunner.query(`CREATE TABLE "UserShift" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "userId" uuid NOT NULL, "shiftId" uuid NOT NULL, "effectiveFrom" date NOT NULL, "effectiveTo" date, CONSTRAINT "PK_2aeece109647347990e601e214c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "Scheduler" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "userId" uuid NOT NULL, "scheduleDate" date NOT NULL, "startTime" TIME NOT NULL, "endTime" TIME NOT NULL, "scheduleType" character varying(20) NOT NULL DEFAULT 'CUSTOM', "workType" character varying(20) NOT NULL DEFAULT 'ONSITE', "reason" character varying(255), "notes" text, "isPaidOvertime" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_a185bb2c6bbf7eb96f5d50ab836" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."Invite_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TYPE "public"."Invite_role_enum" AS ENUM('admin', 'ADMIN', 'employee', 'EMPLOYEE')`);
        await queryRunner.query(`CREATE TABLE "Invite" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "email" text NOT NULL, "token" text NOT NULL, "status" "public"."Invite_status_enum" NOT NULL DEFAULT 'PENDING', "expiresAt" TIMESTAMP NOT NULL, "acceptedAt" TIMESTAMP, "role" "public"."Invite_role_enum" NOT NULL, CONSTRAINT "UQ_7626635e0df019f9cb07fdf5e7f" UNIQUE ("email"), CONSTRAINT "UQ_b67b86d63bfeab362b724da731e" UNIQUE ("token"), CONSTRAINT "PK_7b2bbbebeadf0c35960e46e4a9b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."Request_type_enum" AS ENUM('CHECK_IN', 'CHECK_OUT')`);
        await queryRunner.query(`CREATE TYPE "public"."Request_status_enum" AS ENUM('PENDING', 'APPROVED', 'REJECTED')`);
        await queryRunner.query(`CREATE TABLE "Request" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "code" character varying(20) NOT NULL, "userId" uuid NOT NULL, "attendanceId" uuid NOT NULL, "type" "public"."Request_type_enum" NOT NULL, "date" date NOT NULL, "time" TIME NOT NULL, "reason" text NOT NULL, "status" "public"."Request_status_enum" NOT NULL DEFAULT 'PENDING', "reviewedBy" uuid, "reviewedAt" TIMESTAMP, "reviewNotes" text, CONSTRAINT "PK_23de24dc477765bcc099feae8e5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6cd9e02462ddcd5a380f7e913c" ON "Request" ("userId", "date", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."PayrollAdjustment_adjustmenttype_enum" AS ENUM('ADDITION', 'DEDUCTION')`);
        await queryRunner.query(`CREATE TYPE "public"."PayrollAdjustment_category_enum" AS ENUM('BONUS', 'BENEFIT', 'OVERTIME', 'ALLOWANCE', 'TAX', 'INSURANCE', 'LOAN', 'ADVANCE', 'OTHER', 'ABSENT', 'EARLY_LEAVE', 'LATE')`);
        await queryRunner.query(`CREATE TABLE "PayrollAdjustment" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "payrollId" uuid NOT NULL, "employeeId" uuid NOT NULL, "adjustmentType" "public"."PayrollAdjustment_adjustmenttype_enum" NOT NULL, "category" "public"."PayrollAdjustment_category_enum" NOT NULL, "title" character varying(100) NOT NULL, "description" text, "amount" bigint NOT NULL, "manual" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_9b619783e0b0c29afe35c927e54" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_31763e36e287b10da22c152e3d" ON "PayrollAdjustment" ("companyId", "payrollId", "adjustmentType") `);
        await queryRunner.query(`CREATE TYPE "public"."Payroll_status_enum" AS ENUM('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "Payroll" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "employeeId" uuid NOT NULL, "userId" uuid NOT NULL, "departmentId" uuid, "payrollMonth" integer NOT NULL, "payrollYear" integer NOT NULL, "status" "public"."Payroll_status_enum" NOT NULL DEFAULT 'DRAFT', "basicSalary" bigint NOT NULL, "grossSalary" bigint NOT NULL DEFAULT '0', "netSalary" bigint NOT NULL DEFAULT '0', "incomeTax" bigint NOT NULL DEFAULT '0', "totalAdditions" bigint NOT NULL DEFAULT '0', "totalDeductions" bigint NOT NULL DEFAULT '0', "approvedAt" TIMESTAMP, "approvedBy" uuid, "notes" text, CONSTRAINT "PK_d51036ab72324d7848ec3b78e48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7eb131e46ae7cccdcb8cb8444f" ON "Payroll" ("companyId", "employeeId", "payrollMonth", "payrollYear") `);
        await queryRunner.query(`CREATE TABLE "AttendanceSummary" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "employeeId" uuid NOT NULL, "userId" uuid NOT NULL, "departmentId" uuid, "attendanceMonth" integer NOT NULL, "attendanceYear" integer NOT NULL, "status" character varying(50) NOT NULL, "monthDays" integer NOT NULL DEFAULT '0', "offDays" integer NOT NULL DEFAULT '0', "totalWorkingDays" integer NOT NULL DEFAULT '0', "presentDays" integer NOT NULL DEFAULT '0', "absentDays" integer NOT NULL DEFAULT '0', "leaveDays" integer NOT NULL DEFAULT '0', "publicHolidays" integer NOT NULL DEFAULT '0', "earlyLeaveDays" integer NOT NULL DEFAULT '0', "totalWorkingHours" numeric(5,2) NOT NULL DEFAULT '0', "totalExpectedWorkingHours" numeric(5,2) NOT NULL DEFAULT '0', "totalLockedWorkingHours" numeric(5,2) NOT NULL DEFAULT '0', "totalEarlyLeaveHours" numeric(5,2) NOT NULL DEFAULT '0', "notes" text, CONSTRAINT "PK_1e1103a775b76c9187f989305eb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0657d6bb2771bc5cf8367f49b5" ON "AttendanceSummary" ("companyId", "employeeId", "attendanceMonth", "attendanceYear") `);
        await queryRunner.query(`CREATE TABLE "Announcement" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "title" character varying(255) NOT NULL, "description" text NOT NULL, CONSTRAINT "PK_1aad4a24ede009867311c065675" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eed7e5bf847bd54abfd221e151" ON "Announcement" ("companyId", "deleted") `);
        await queryRunner.query(`CREATE TYPE "public"."Notification_type_enum" AS ENUM('LEAVE_STATUS', 'PAYSLIP', 'ANNOUNCEMENT', 'CHECK_IN_REMINDER', 'CHECK_OUT_REMINDER', 'GENERAL')`);
        await queryRunner.query(`CREATE TABLE "Notification" ("id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL, "active" boolean NOT NULL DEFAULT '1', "createdBy" text NOT NULL, "createdById" uuid NOT NULL, "modifiedAt" TIMESTAMP, "modifiedBy" text, "modifiedById" uuid, "deleted" boolean NOT NULL DEFAULT '0', "companyId" uuid NOT NULL, "recipientUserId" uuid NOT NULL, "title" character varying(255) NOT NULL, "message" text NOT NULL, "type" "public"."Notification_type_enum" NOT NULL DEFAULT 'GENERAL', "isRead" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_da18f6446b6fea585f01d03f56c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_be8ebb2ff3b4e8b6ee7093559e" ON "Notification" ("companyId", "recipientUserId", "isRead") `);
        await queryRunner.query(`CREATE TABLE "Role_Privilege" ("privilegeId" uuid NOT NULL, "roleId" uuid NOT NULL, CONSTRAINT "PK_7ad4e7c8db6da2144e1f8ac1ce8" PRIMARY KEY ("privilegeId", "roleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f8010badf2d4285b8a0e6188c" ON "Role_Privilege" ("privilegeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_19c51cf01b8910786e1e4c2140" ON "Role_Privilege" ("roleId") `);
        await queryRunner.query(`ALTER TABLE "Verification" ADD CONSTRAINT "FK_6f79e128705e55fda4b4434f069" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Designation" ADD CONSTRAINT "FK_6696a24fc164bb2949bf3325a32" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Designation" ADD CONSTRAINT "FK_2d31065493fa363d75d2ea47f65" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PublicHoliday" ADD CONSTRAINT "FK_5fc505bad6e7f7e0b95cbdfaab2" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PublicHoliday" ADD CONSTRAINT "FK_d94a7c670138e1c946e2debbcea" FOREIGN KEY ("whichCountryId") REFERENCES "Country"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PublicHoliday" ADD CONSTRAINT "FK_89193a043b50b8c5e22803e5d29" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WorkingDays" ADD CONSTRAINT "FK_60d947b0ee76c98545bab4eedd5" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WorkingDays" ADD CONSTRAINT "FK_53cff0beebf6af2a33e2e2ac152" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Shift" ADD CONSTRAINT "FK_e601c6f808fe2530ea8f328df27" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Shift" ADD CONSTRAINT "FK_15f1bd8e5a0cb369bb8647ff36d" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Department" ADD CONSTRAINT "FK_66d76137d3d3f2562dd847bbbf2" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Department" ADD CONSTRAINT "FK_dee1b6f0786830dffbc9036c848" FOREIGN KEY ("parentId") REFERENCES "Department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Benefit" ADD CONSTRAINT "FK_cd35c3d927ded094ef4422cb47c" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Benefit" ADD CONSTRAINT "FK_aa18429483604d648bd00423734" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Employee" ADD CONSTRAINT "FK_b0183e9f89fdcfc0bbb1851c23c" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Employee" ADD CONSTRAINT "FK_c1ec0cb63387d4c8bb2892bc002" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Employee" ADD CONSTRAINT "FK_9e6414e021aa19c44de3d5f9a79" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Employee" ADD CONSTRAINT "FK_78438fa290e93e14fdfb868832a" FOREIGN KEY ("designationId") REFERENCES "Designation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Employee" ADD CONSTRAINT "FK_4fd059c2b9ef43a65d749bfe376" FOREIGN KEY ("shiftId") REFERENCES "Shift"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EmployeeBenefit" ADD CONSTRAINT "FK_f7dc6b2ea40a0211791bf4a9b4c" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EmployeeBenefit" ADD CONSTRAINT "FK_93011ffd1b0ffef6b64c5d6da9e" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EmployeeBenefit" ADD CONSTRAINT "FK_c3b901a1402e199005e4550d99f" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "EmployeeBenefit" ADD CONSTRAINT "FK_fcc360437062ebe32d5184ec132" FOREIGN KEY ("benefitId") REFERENCES "Benefit"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Project" ADD CONSTRAINT "FK_4680847189ee85f14c94384679e" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Role" ADD CONSTRAINT "FK_69d1595a6f276584089343d5dec" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "User" ADD CONSTRAINT "FK_9ba29740add33d9319e52f58257" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "User" ADD CONSTRAINT "FK_0b8c60cc29663fa5b9fb108edd7" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ToDo" ADD CONSTRAINT "FK_365395a549e42d5d24124c6003c" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ToDo" ADD CONSTRAINT "FK_4a3dd24d851f57ceb5a1f31e252" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ActivityLog" ADD CONSTRAINT "FK_52f6959a787992b757256a6628f" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Candidate" ADD CONSTRAINT "FK_1cc95e86e8ff14d351dabc8ca92" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Skill" ADD CONSTRAINT "FK_0bf704b248904f63df35de11b6f" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AssessmentScore" ADD CONSTRAINT "FK_bede66361d4f6417d228314e20b" FOREIGN KEY ("assessmentId") REFERENCES "Assessment"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AssessmentScore" ADD CONSTRAINT "FK_fa0f2fd9be2edc4d80612ba5701" FOREIGN KEY ("skillId") REFERENCES "Skill"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Assessment" ADD CONSTRAINT "FK_fb109e783eafb86d0fcbdd45110" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Assessment" ADD CONSTRAINT "FK_1ff8e4795d381a286ae2682dc36" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LeaveType" ADD CONSTRAINT "FK_1996b44d7f89a34189f77b59e4a" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LeaveType" ADD CONSTRAINT "FK_e6f99837dcb28713f7448a414fa" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Break" ADD CONSTRAINT "FK_3107a63780b146b03b7974ebdf8" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Break" ADD CONSTRAINT "FK_cb31f7b5972bbad63636de89ed9" FOREIGN KEY ("attendanceId") REFERENCES "Attendance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Break" ADD CONSTRAINT "FK_06ee1ed3cb97d144dbef21d2d1e" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Vacation" ADD CONSTRAINT "FK_7393b7e1d4292fd7d1a9203ae0e" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Vacation" ADD CONSTRAINT "FK_6fe8ea1328f5aaa435eb81f7923" FOREIGN KEY ("requestedBy") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Vacation" ADD CONSTRAINT "FK_5430db221722885e17d5feaaa37" FOREIGN KEY ("actionBy") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Vacation" ADD CONSTRAINT "FK_e7ca0ccaba09fc3bbee95937156" FOREIGN KEY ("typeId") REFERENCES "LeaveType"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Attendance" ADD CONSTRAINT "FK_346637d92ed022c234f73edc404" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Attendance" ADD CONSTRAINT "FK_f85d074c0eb90a5506797c8a6e6" FOREIGN KEY ("vacationId") REFERENCES "Vacation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Attendance" ADD CONSTRAINT "FK_811c3fd99338f6049cea5453df7" FOREIGN KEY ("publicHolidayId") REFERENCES "PublicHoliday"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Attendance" ADD CONSTRAINT "FK_0debaefb727a25bbe38121c5b4f" FOREIGN KEY ("remoteWorkId") REFERENCES "Vacation"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Attendance" ADD CONSTRAINT "FK_662f0968ac6febc10772f3329a0" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Attendance" ADD CONSTRAINT "FK_a3b79491051c8ec1fd088652258" FOREIGN KEY ("shiftId") REFERENCES "Shift"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserShift" ADD CONSTRAINT "FK_d0b9e717e1069fc722af9d7f4fd" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserShift" ADD CONSTRAINT "FK_ab2c55c9187277eadd9f3123e91" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserShift" ADD CONSTRAINT "FK_dec89b6a02ae5e656e378cb9fb2" FOREIGN KEY ("shiftId") REFERENCES "Shift"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Scheduler" ADD CONSTRAINT "FK_85c59b12791d8ddf8567e7cdcbd" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Scheduler" ADD CONSTRAINT "FK_b5add57015707638978d8941d6f" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Invite" ADD CONSTRAINT "FK_4f3e653d95503664f8a3159b42c" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Request" ADD CONSTRAINT "FK_591b344ff77895b973e39455ef6" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Request" ADD CONSTRAINT "FK_cdaf52464b00ac3016a8f6110fd" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Request" ADD CONSTRAINT "FK_e2b78454bc65e99b44075dc90a7" FOREIGN KEY ("reviewedBy") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Request" ADD CONSTRAINT "FK_f75a5d13ff3f02d5a092e8c1eff" FOREIGN KEY ("attendanceId") REFERENCES "Attendance"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PayrollAdjustment" ADD CONSTRAINT "FK_e5696d8901786ef27b543dfb16a" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PayrollAdjustment" ADD CONSTRAINT "FK_a20bc595d76bbef061423ddaf57" FOREIGN KEY ("payrollId") REFERENCES "Payroll"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PayrollAdjustment" ADD CONSTRAINT "FK_4e12498c3996d84dca362b5f038" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payroll" ADD CONSTRAINT "FK_16fb8967aefd3bc8f1d9c25cc9a" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payroll" ADD CONSTRAINT "FK_ff6d203a3ea3e634bba74d30899" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payroll" ADD CONSTRAINT "FK_736f6f6eb1caf42cbf7816bd72c" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payroll" ADD CONSTRAINT "FK_80ef18381744cb75a29fc7a9f49" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Payroll" ADD CONSTRAINT "FK_048e04656c5867c997592ff19ad" FOREIGN KEY ("approvedBy") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AttendanceSummary" ADD CONSTRAINT "FK_9567f0039a2d5fe587aa651af7b" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AttendanceSummary" ADD CONSTRAINT "FK_fa3499702f8ae1dd780f74a4f07" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AttendanceSummary" ADD CONSTRAINT "FK_8088d50a1b908c2b5314a40dad2" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "AttendanceSummary" ADD CONSTRAINT "FK_b8b197ed886345e850eec980879" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Announcement" ADD CONSTRAINT "FK_dba28c517d8deb15dc90d62e4f6" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Notification" ADD CONSTRAINT "FK_49e47fd3bbbffd3a976c9953218" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Role_Privilege" ADD CONSTRAINT "FK_8f8010badf2d4285b8a0e6188cf" FOREIGN KEY ("privilegeId") REFERENCES "Privilege"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "Role_Privilege" ADD CONSTRAINT "FK_19c51cf01b8910786e1e4c21404" FOREIGN KEY ("roleId") REFERENCES "Role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Role_Privilege" DROP CONSTRAINT "FK_19c51cf01b8910786e1e4c21404"`);
        await queryRunner.query(`ALTER TABLE "Role_Privilege" DROP CONSTRAINT "FK_8f8010badf2d4285b8a0e6188cf"`);
        await queryRunner.query(`ALTER TABLE "Notification" DROP CONSTRAINT "FK_49e47fd3bbbffd3a976c9953218"`);
        await queryRunner.query(`ALTER TABLE "Announcement" DROP CONSTRAINT "FK_dba28c517d8deb15dc90d62e4f6"`);
        await queryRunner.query(`ALTER TABLE "AttendanceSummary" DROP CONSTRAINT "FK_b8b197ed886345e850eec980879"`);
        await queryRunner.query(`ALTER TABLE "AttendanceSummary" DROP CONSTRAINT "FK_8088d50a1b908c2b5314a40dad2"`);
        await queryRunner.query(`ALTER TABLE "AttendanceSummary" DROP CONSTRAINT "FK_fa3499702f8ae1dd780f74a4f07"`);
        await queryRunner.query(`ALTER TABLE "AttendanceSummary" DROP CONSTRAINT "FK_9567f0039a2d5fe587aa651af7b"`);
        await queryRunner.query(`ALTER TABLE "Payroll" DROP CONSTRAINT "FK_048e04656c5867c997592ff19ad"`);
        await queryRunner.query(`ALTER TABLE "Payroll" DROP CONSTRAINT "FK_80ef18381744cb75a29fc7a9f49"`);
        await queryRunner.query(`ALTER TABLE "Payroll" DROP CONSTRAINT "FK_736f6f6eb1caf42cbf7816bd72c"`);
        await queryRunner.query(`ALTER TABLE "Payroll" DROP CONSTRAINT "FK_ff6d203a3ea3e634bba74d30899"`);
        await queryRunner.query(`ALTER TABLE "Payroll" DROP CONSTRAINT "FK_16fb8967aefd3bc8f1d9c25cc9a"`);
        await queryRunner.query(`ALTER TABLE "PayrollAdjustment" DROP CONSTRAINT "FK_4e12498c3996d84dca362b5f038"`);
        await queryRunner.query(`ALTER TABLE "PayrollAdjustment" DROP CONSTRAINT "FK_a20bc595d76bbef061423ddaf57"`);
        await queryRunner.query(`ALTER TABLE "PayrollAdjustment" DROP CONSTRAINT "FK_e5696d8901786ef27b543dfb16a"`);
        await queryRunner.query(`ALTER TABLE "Request" DROP CONSTRAINT "FK_f75a5d13ff3f02d5a092e8c1eff"`);
        await queryRunner.query(`ALTER TABLE "Request" DROP CONSTRAINT "FK_e2b78454bc65e99b44075dc90a7"`);
        await queryRunner.query(`ALTER TABLE "Request" DROP CONSTRAINT "FK_cdaf52464b00ac3016a8f6110fd"`);
        await queryRunner.query(`ALTER TABLE "Request" DROP CONSTRAINT "FK_591b344ff77895b973e39455ef6"`);
        await queryRunner.query(`ALTER TABLE "Invite" DROP CONSTRAINT "FK_4f3e653d95503664f8a3159b42c"`);
        await queryRunner.query(`ALTER TABLE "Scheduler" DROP CONSTRAINT "FK_b5add57015707638978d8941d6f"`);
        await queryRunner.query(`ALTER TABLE "Scheduler" DROP CONSTRAINT "FK_85c59b12791d8ddf8567e7cdcbd"`);
        await queryRunner.query(`ALTER TABLE "UserShift" DROP CONSTRAINT "FK_dec89b6a02ae5e656e378cb9fb2"`);
        await queryRunner.query(`ALTER TABLE "UserShift" DROP CONSTRAINT "FK_ab2c55c9187277eadd9f3123e91"`);
        await queryRunner.query(`ALTER TABLE "UserShift" DROP CONSTRAINT "FK_d0b9e717e1069fc722af9d7f4fd"`);
        await queryRunner.query(`ALTER TABLE "Attendance" DROP CONSTRAINT "FK_a3b79491051c8ec1fd088652258"`);
        await queryRunner.query(`ALTER TABLE "Attendance" DROP CONSTRAINT "FK_662f0968ac6febc10772f3329a0"`);
        await queryRunner.query(`ALTER TABLE "Attendance" DROP CONSTRAINT "FK_0debaefb727a25bbe38121c5b4f"`);
        await queryRunner.query(`ALTER TABLE "Attendance" DROP CONSTRAINT "FK_811c3fd99338f6049cea5453df7"`);
        await queryRunner.query(`ALTER TABLE "Attendance" DROP CONSTRAINT "FK_f85d074c0eb90a5506797c8a6e6"`);
        await queryRunner.query(`ALTER TABLE "Attendance" DROP CONSTRAINT "FK_346637d92ed022c234f73edc404"`);
        await queryRunner.query(`ALTER TABLE "Vacation" DROP CONSTRAINT "FK_e7ca0ccaba09fc3bbee95937156"`);
        await queryRunner.query(`ALTER TABLE "Vacation" DROP CONSTRAINT "FK_5430db221722885e17d5feaaa37"`);
        await queryRunner.query(`ALTER TABLE "Vacation" DROP CONSTRAINT "FK_6fe8ea1328f5aaa435eb81f7923"`);
        await queryRunner.query(`ALTER TABLE "Vacation" DROP CONSTRAINT "FK_7393b7e1d4292fd7d1a9203ae0e"`);
        await queryRunner.query(`ALTER TABLE "Break" DROP CONSTRAINT "FK_06ee1ed3cb97d144dbef21d2d1e"`);
        await queryRunner.query(`ALTER TABLE "Break" DROP CONSTRAINT "FK_cb31f7b5972bbad63636de89ed9"`);
        await queryRunner.query(`ALTER TABLE "Break" DROP CONSTRAINT "FK_3107a63780b146b03b7974ebdf8"`);
        await queryRunner.query(`ALTER TABLE "LeaveType" DROP CONSTRAINT "FK_e6f99837dcb28713f7448a414fa"`);
        await queryRunner.query(`ALTER TABLE "LeaveType" DROP CONSTRAINT "FK_1996b44d7f89a34189f77b59e4a"`);
        await queryRunner.query(`ALTER TABLE "Assessment" DROP CONSTRAINT "FK_1ff8e4795d381a286ae2682dc36"`);
        await queryRunner.query(`ALTER TABLE "Assessment" DROP CONSTRAINT "FK_fb109e783eafb86d0fcbdd45110"`);
        await queryRunner.query(`ALTER TABLE "AssessmentScore" DROP CONSTRAINT "FK_fa0f2fd9be2edc4d80612ba5701"`);
        await queryRunner.query(`ALTER TABLE "AssessmentScore" DROP CONSTRAINT "FK_bede66361d4f6417d228314e20b"`);
        await queryRunner.query(`ALTER TABLE "Skill" DROP CONSTRAINT "FK_0bf704b248904f63df35de11b6f"`);
        await queryRunner.query(`ALTER TABLE "Candidate" DROP CONSTRAINT "FK_1cc95e86e8ff14d351dabc8ca92"`);
        await queryRunner.query(`ALTER TABLE "ActivityLog" DROP CONSTRAINT "FK_52f6959a787992b757256a6628f"`);
        await queryRunner.query(`ALTER TABLE "ToDo" DROP CONSTRAINT "FK_4a3dd24d851f57ceb5a1f31e252"`);
        await queryRunner.query(`ALTER TABLE "ToDo" DROP CONSTRAINT "FK_365395a549e42d5d24124c6003c"`);
        await queryRunner.query(`ALTER TABLE "User" DROP CONSTRAINT "FK_0b8c60cc29663fa5b9fb108edd7"`);
        await queryRunner.query(`ALTER TABLE "User" DROP CONSTRAINT "FK_9ba29740add33d9319e52f58257"`);
        await queryRunner.query(`ALTER TABLE "Role" DROP CONSTRAINT "FK_69d1595a6f276584089343d5dec"`);
        await queryRunner.query(`ALTER TABLE "Project" DROP CONSTRAINT "FK_4680847189ee85f14c94384679e"`);
        await queryRunner.query(`ALTER TABLE "EmployeeBenefit" DROP CONSTRAINT "FK_fcc360437062ebe32d5184ec132"`);
        await queryRunner.query(`ALTER TABLE "EmployeeBenefit" DROP CONSTRAINT "FK_c3b901a1402e199005e4550d99f"`);
        await queryRunner.query(`ALTER TABLE "EmployeeBenefit" DROP CONSTRAINT "FK_93011ffd1b0ffef6b64c5d6da9e"`);
        await queryRunner.query(`ALTER TABLE "EmployeeBenefit" DROP CONSTRAINT "FK_f7dc6b2ea40a0211791bf4a9b4c"`);
        await queryRunner.query(`ALTER TABLE "Employee" DROP CONSTRAINT "FK_4fd059c2b9ef43a65d749bfe376"`);
        await queryRunner.query(`ALTER TABLE "Employee" DROP CONSTRAINT "FK_78438fa290e93e14fdfb868832a"`);
        await queryRunner.query(`ALTER TABLE "Employee" DROP CONSTRAINT "FK_9e6414e021aa19c44de3d5f9a79"`);
        await queryRunner.query(`ALTER TABLE "Employee" DROP CONSTRAINT "FK_c1ec0cb63387d4c8bb2892bc002"`);
        await queryRunner.query(`ALTER TABLE "Employee" DROP CONSTRAINT "FK_b0183e9f89fdcfc0bbb1851c23c"`);
        await queryRunner.query(`ALTER TABLE "Benefit" DROP CONSTRAINT "FK_aa18429483604d648bd00423734"`);
        await queryRunner.query(`ALTER TABLE "Benefit" DROP CONSTRAINT "FK_cd35c3d927ded094ef4422cb47c"`);
        await queryRunner.query(`ALTER TABLE "Department" DROP CONSTRAINT "FK_dee1b6f0786830dffbc9036c848"`);
        await queryRunner.query(`ALTER TABLE "Department" DROP CONSTRAINT "FK_66d76137d3d3f2562dd847bbbf2"`);
        await queryRunner.query(`ALTER TABLE "Shift" DROP CONSTRAINT "FK_15f1bd8e5a0cb369bb8647ff36d"`);
        await queryRunner.query(`ALTER TABLE "Shift" DROP CONSTRAINT "FK_e601c6f808fe2530ea8f328df27"`);
        await queryRunner.query(`ALTER TABLE "WorkingDays" DROP CONSTRAINT "FK_53cff0beebf6af2a33e2e2ac152"`);
        await queryRunner.query(`ALTER TABLE "WorkingDays" DROP CONSTRAINT "FK_60d947b0ee76c98545bab4eedd5"`);
        await queryRunner.query(`ALTER TABLE "PublicHoliday" DROP CONSTRAINT "FK_89193a043b50b8c5e22803e5d29"`);
        await queryRunner.query(`ALTER TABLE "PublicHoliday" DROP CONSTRAINT "FK_d94a7c670138e1c946e2debbcea"`);
        await queryRunner.query(`ALTER TABLE "PublicHoliday" DROP CONSTRAINT "FK_5fc505bad6e7f7e0b95cbdfaab2"`);
        await queryRunner.query(`ALTER TABLE "Designation" DROP CONSTRAINT "FK_2d31065493fa363d75d2ea47f65"`);
        await queryRunner.query(`ALTER TABLE "Designation" DROP CONSTRAINT "FK_6696a24fc164bb2949bf3325a32"`);
        await queryRunner.query(`ALTER TABLE "Verification" DROP CONSTRAINT "FK_6f79e128705e55fda4b4434f069"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19c51cf01b8910786e1e4c2140"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f8010badf2d4285b8a0e6188c"`);
        await queryRunner.query(`DROP TABLE "Role_Privilege"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be8ebb2ff3b4e8b6ee7093559e"`);
        await queryRunner.query(`DROP TABLE "Notification"`);
        await queryRunner.query(`DROP TYPE "public"."Notification_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eed7e5bf847bd54abfd221e151"`);
        await queryRunner.query(`DROP TABLE "Announcement"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0657d6bb2771bc5cf8367f49b5"`);
        await queryRunner.query(`DROP TABLE "AttendanceSummary"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7eb131e46ae7cccdcb8cb8444f"`);
        await queryRunner.query(`DROP TABLE "Payroll"`);
        await queryRunner.query(`DROP TYPE "public"."Payroll_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31763e36e287b10da22c152e3d"`);
        await queryRunner.query(`DROP TABLE "PayrollAdjustment"`);
        await queryRunner.query(`DROP TYPE "public"."PayrollAdjustment_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."PayrollAdjustment_adjustmenttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cd9e02462ddcd5a380f7e913c"`);
        await queryRunner.query(`DROP TABLE "Request"`);
        await queryRunner.query(`DROP TYPE "public"."Request_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Request_type_enum"`);
        await queryRunner.query(`DROP TABLE "Invite"`);
        await queryRunner.query(`DROP TYPE "public"."Invite_role_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Invite_status_enum"`);
        await queryRunner.query(`DROP TABLE "Scheduler"`);
        await queryRunner.query(`DROP TABLE "UserShift"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5742abb86c9f08df0f719e9571"`);
        await queryRunner.query(`DROP TABLE "Attendance"`);
        await queryRunner.query(`DROP TYPE "public"."Attendance_presentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Attendance_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5532ee2ca08742691f688d8d58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1040e7608de80573a46702a7f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69caf3aded343eb70907d36a90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_572b94fc3c022405e5fb377a9d"`);
        await queryRunner.query(`DROP TABLE "Vacation"`);
        await queryRunner.query(`DROP TYPE "public"."Vacation_requesttype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Vacation_progressstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Vacation_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b6f6f0dcfa8f1bb0a6f49bb1b"`);
        await queryRunner.query(`DROP TABLE "Break"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f5d6eefea9367a9742b9a05226"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ee86dd2a9a510ee0b92d124d18"`);
        await queryRunner.query(`DROP TABLE "LeaveType"`);
        await queryRunner.query(`DROP TYPE "public"."LeaveType_genderspecific_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d28f884c64218d820c06693a65"`);
        await queryRunner.query(`DROP TABLE "Assessment"`);
        await queryRunner.query(`DROP TABLE "AssessmentScore"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1968c96fe4a16f80dbc4aab21"`);
        await queryRunner.query(`DROP TABLE "Skill"`);
        await queryRunner.query(`DROP TABLE "Candidate"`);
        await queryRunner.query(`DROP TYPE "public"."Candidate_stage_enum"`);
        await queryRunner.query(`DROP TABLE "AuditLog"`);
        await queryRunner.query(`DROP TABLE "ActivityLog"`);
        await queryRunner.query(`DROP TABLE "ToDo"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b0e7a0342661f17cb2ab80cb9"`);
        await queryRunner.query(`DROP TABLE "MasterEnum"`);
        await queryRunner.query(`DROP TABLE "Company"`);
        await queryRunner.query(`DROP TABLE "User"`);
        await queryRunner.query(`DROP TABLE "Role"`);
        await queryRunner.query(`DROP TABLE "Project"`);
        await queryRunner.query(`DROP TYPE "public"."Project_status_enum"`);
        await queryRunner.query(`DROP TABLE "EmployeeBenefit"`);
        await queryRunner.query(`DROP TABLE "Employee"`);
        await queryRunner.query(`DROP TYPE "public"."Employee_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c3ab6e3d475ec045deb56308a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08551d108120400623a97166ab"`);
        await queryRunner.query(`DROP TABLE "Benefit"`);
        await queryRunner.query(`DROP TYPE "public"."Benefit_frequency_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Benefit_valuetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Benefit_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3eee0ade0f427f8d9f7f71a0ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1fb48e609614d5b97b84941122"`);
        await queryRunner.query(`DROP TABLE "Department"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3915799d9806645f4f436b86ae"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_db8d7a9947738c01bfecaf08f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_712a6cd08fb8b534f23311277f"`);
        await queryRunner.query(`DROP TABLE "Shift"`);
        await queryRunner.query(`DROP TYPE "public"."Shift_shifttype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a403a10d3dacecc66dfa89a23"`);
        await queryRunner.query(`DROP TABLE "WorkingDays"`);
        await queryRunner.query(`DROP TYPE "public"."WorkingDays_dayname_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e706c4bcc13d49c1550d9a308"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0718e184666cb9645d29a78e7a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89193a043b50b8c5e22803e5d2"`);
        await queryRunner.query(`DROP TABLE "PublicHoliday"`);
        await queryRunner.query(`DROP TYPE "public"."PublicHoliday_type_enum"`);
        await queryRunner.query(`DROP TABLE "Country"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a18e8c0f02927b845e40d84f2f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6042cd2ab7b046e181a4dba91a"`);
        await queryRunner.query(`DROP TABLE "Designation"`);
        await queryRunner.query(`DROP TYPE "public"."Designation_levelhierarchy_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31ffc38ebfed70d24cfeea84d6"`);
        await queryRunner.query(`DROP TABLE "Verification"`);
        await queryRunner.query(`DROP TYPE "public"."Verification_whichpurpose_enum"`);
        await queryRunner.query(`DROP TYPE "public"."Verification_type_enum"`);
        await queryRunner.query(`DROP TABLE "Privilege"`);
    }

}
