import { DependencyContainer } from "tsyringe";
import { CompanyService } from "../company-service";
import { PrivilegeService } from "../privilege-service";
import { RoleService } from "../role-service";
import { UserService } from "../user-service";
import { AuthService } from "../auth-service";
import { ToDoService } from "../todo-service";
import { DepartmentService } from "../department-service";
import { DesignationService } from "../designation-service";
import { CandidateService } from "../candidate-service";
import { ProjectService } from "../project-service";
import { SkillService } from "../skill-service";
import { AssessmentService } from "../assessment-service";
import { CountryService } from "../country-service";
import { LeaveTypeService } from "../leave-type-service";
import { PublicHolidayService } from "../public-holiday-service";
import { EmployeeService } from "../employee-service";
import { AttendanceService } from "../attendance-service";
import { AttendanceBreakService } from "../attendance-break-service";
import { VacationService } from "../vacation-service";
import { WorkingDaysService } from "../working-days-service";
import { ShiftService } from "../shift-service";
import { UserShiftService } from "../user-shift-service";
import { SchedulerService } from "../scheduler-service";
import { MasterEnumService } from "../master-enum-service";
import { InviteService } from "../invite-service";
import { RequestService } from "../request-service";
import { BenefitService } from "../benefit-service";
import { EmployeeBenefitService } from "../employee-benefit-service";
import { UploadService } from "../upload-service";
import { PayrollService } from "../payroll-service";
import { PayrollAdjustmentService } from "../payroll-adjustment-service";
import { AnnouncementService } from "../announcement-service";
import { NotificationService } from "../notification-service";
import { TaxCalculatorService } from "../tax-calculator-service";
import { AttendanceSummaryService } from "../attendance-summary-service";
import { EmployeeMilestoneService } from "../employee-milestone-service";

export const registerServices = (container: DependencyContainer) => {
    container.register<CompanyService>('CompanyService', CompanyService);
    container.register<CountryService>('CountryService', CountryService);
    container.register<MasterEnumService>('MasterEnumService', MasterEnumService);
    container.register<UserService>('UserService', UserService);
    container.register<AuthService>('AuthService', AuthService);
    container.register<PrivilegeService>('PrivilegeService', PrivilegeService);
    container.register<RoleService>('RoleService', RoleService);
    container.register<ToDoService>('ToDoService', ToDoService);
    container.register<DepartmentService>('DepartmentService', DepartmentService);
    container.register<DesignationService>('DesignationService', DesignationService);
    container.register<CandidateService>('CandidateService', CandidateService);
    container.register<ProjectService>('ProjectService', ProjectService);
    container.register<SkillService>('SkillService', SkillService);
    container.register<AssessmentService>('AssessmentService', AssessmentService);
    container.register<LeaveTypeService>('LeaveTypeService', LeaveTypeService);
    container.register<PublicHolidayService>('PublicHolidayService', PublicHolidayService);
    container.register<EmployeeService>('EmployeeService', EmployeeService);
    container.register<EmployeeMilestoneService>('EmployeeMilestoneService', EmployeeMilestoneService);
    container.register<AttendanceService>('AttendanceService', AttendanceService);
    container.register<AttendanceBreakService>('AttendanceBreakService', AttendanceBreakService);
    container.register<VacationService>('VacationService', VacationService);
    container.register<WorkingDaysService>('WorkingDaysService', WorkingDaysService);
    container.register<ShiftService>('ShiftService', ShiftService);
    container.register<UserShiftService>('UserShiftService', UserShiftService);
    container.register<SchedulerService>('SchedulerService', SchedulerService);
    container.register<InviteService>('InviteService', InviteService);
    container.register<RequestService>('RequestService', RequestService);
    container.register<BenefitService>('BenefitService', BenefitService);
    container.register<EmployeeBenefitService>('EmployeeBenefitService', EmployeeBenefitService);
    container.register<UploadService>('UploadService', UploadService);
    container.register<PayrollService>('PayrollService', PayrollService);
    container.register<PayrollAdjustmentService>('PayrollAdjustmentService', PayrollAdjustmentService);
    container.register<TaxCalculatorService>('TaxCalculatorService', TaxCalculatorService);
    container.register<AttendanceSummaryService>('AttendanceSummaryService', AttendanceSummaryService);
    container.register<AnnouncementService>('AnnouncementService', AnnouncementService);
    container.register<NotificationService>('NotificationService', NotificationService);

}